version: '3'

services:
  # This is the private app
  app1:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile.service01
    networks:
      - proxy-network
    volumes:
      - ./service01:/app
    container_name: service01
    command: uvicorn main:app --host 0.0.0.0 --port 3000 --reload
    expose:
      - 3000 # This is the port that the app listens to and that the app2 will use to communicate with app1

  # This is the public app
  app2:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile.service02
    ports:
      - 8002:3000 # This is the port that the app2 will listen to
    networks:
      - proxy-network
    container_name: service02
    command: uvicorn main:app --host 0.0.0.0 --port 3000 --reload

  # Nginx for managing the proxy, using only the public apps
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - proxy-network
    depends_on:
      - app2

networks:
  proxy-network:
